import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const WulkanDisplay = localFont({
  src: [
    {
      path: "../../public/assets/fonts/WulkanDisplay-Regular.woff2",
      weight: '400',
    },
    {
      path: "../../public/assets/fonts/WulkanDisplay-Medium.woff2",
      weight: '500',
    },
    {
      path: "../../public/assets/fonts/WulkanDisplay-SemiBold.woff2",
      weight: '600',
    },
    {
      path: "../../public/assets/fonts/WulkanDisplay-Bold.woff2",
      weight: '700',
    },
  ],
  display: 'swap',
  variable: '--font-wulkan-display',
})

const OpenSauceOne = localFont({
  src: [
    {
      path: "../../public/assets/fonts/OpenSauceOne-Regular.woff2",
      weight: '400',
    },
    {
      path: "../../public/assets/fonts/OpenSauceOne-Medium.woff2",
      weight: '500',
    },
    {
      path: "../../public/assets/fonts/OpenSauceOne-SemiBold.woff2",
      weight: '600',
    },
    {
      path: "../../public/assets/fonts/OpenSauceOne-Bold.woff2",
      weight: '700',
    },
  ],
  display: 'swap',
  variable: '--font-open-sauce-one',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${WulkanDisplay.variable} ${OpenSauceOne.variable} antialiased bg-white`}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
